apiVersion: v1
kind: Service
metadata:
  name: wayank-service
spec:
  selector:
    app: wayank-deployment1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort


